CREATE TABLE Book (
  ISBN VARCHAR(13) PRIMARY KEY,
  Title VARCHAR(100) NOT NULL,
  Price INT CHECK (Price >= 0),
  Inventory_Quantity INT CHECK (Inventory_Quantity >= 0)
);

CREATE TABLE Customer (
  UID VARCHAR(10) PRIMARY KEY,
  Name VARCHAR(50) NOT NULL,
  Address VARCHAR(200) NOT NULL
);

CREATE TABLE OrderR (
  OID VARCHAR(10) PRIMARY KEY,
  UID VARCHAR(10) NOT NULL,
  Order_Date DATETIME NOT NULL,
  Order_ISBN VARCHAR(13) NOT NULL,
  Order_Quantity INT CHECK (Order_Quantity > 0),
  Shipping_Status VARCHAR(20) NOT NULL,
  FOREIGN KEY (UID) REFERENCES Customer (UID),
  FOREIGN KEY (Order_ISBN) REFERENCES Book (ISBN)
);

CREATE TABLE Authors (
  aid VARCHAR(10) PRIMARY KEY,
  aname VARCHAR(50) NOT NULL
);


CREATE TABLE Place (
  UID VARCHAR(10) NOT NULL,
  OID VARCHAR(10) NOT NULL,
  Order_ISBN VARCHAR(13) NOT NULL,
  PRIMARY KEY (UID, OID),
  FOREIGN KEY (UID) REFERENCES Customer (UID),
  FOREIGN KEY (OID) REFERENCES OrderR (OID),
  FOREIGN KEY (Order_ISBN) REFERENCES Book (ISBN)
);

CREATE TABLE Include (
  OID VARCHAR(10) NOT NULL,
  ISBN VARCHAR(13) NOT NULL,
  Quantity INT CHECK (Quantity > 0),
  PRIMARY KEY (OID, ISBN),
  FOREIGN KEY (OID) REFERENCES OrderR (OID),
  FOREIGN KEY (ISBN) REFERENCES Book (ISBN)
);

CREATE TABLE WrittenBy (
  ISBN VARCHAR(13) NOT NULL,
  aid VARCHAR(10) NOT NULL,
  PRIMARY KEY (ISBN, aid),
  FOREIGN KEY (ISBN) REFERENCES Book (ISBN),
  FOREIGN KEY (aid) REFERENCES Authors (aid)
);

